- hosts: application-server
  become: yes
  become_method: sudo

  tasks:
    - name: ensure group vagrant exists
      group: name=vagrant state=present

    - name: ensure user vagrant exists
      user: name=vagrant group=vagrant state=present

    - name: install required package
      apt: name="{{ item }}" state=present
      with_items:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - python-docker
        - python-pip

    - name: add Docker's official GPG key
      apt_key: url="http://apt.dockerproject.org/gpg" state=present

    - name: add Docker's repository
      apt_repository: repo="deb https://apt.dockerproject.org/repo/ ubuntu-xenial main" update_cache=yes

    - name: install latest Docker Engine
      apt: name="docker-engine"

    - name: add user vagrant to group docker
      user: name=vagrant groups=docker state=present

    - name: install docker compose
      pip: name=docker-compose
