- hosts: localhost
  vars:
    registry_hostname: localhost
  tasks:
    - name: build and push tomcat image
      docker_image:
        name: sparsick/tomcat
        dockerfile: tomcat.df
        path: "{{ playbook_dir }}/../docker-image-ansible"
        push: yes
        repository: "{{ registry_hostname }}:5000/sparsick/tomcat:ansible"

    - name: build and push mysql image
      docker_image:
        name: sparsick/mysql
        dockerfile: mysql.df
        path: "{{ playbook_dir }}/../docker-image-ansible"
        push: yes
        repository: "{{ registry_hostname }}:5000/sparsick/mysql:ansible"
# check if image is really pushed in repository
